apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-earphones:242a430ee2904ddc0302c57c8267da538f697f9c
        ports:
        - containerPort: 80
