apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-backend:1d7995bda6ab887f3d2a62e72d6d31e540576c5c
          ports:
            - containerPort: 5000
