apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 905418310012.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:d2c1aa12aea9072b09de2eeeeaf04c5b56b34fe4
          ports:
            - containerPort: 5000
