apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:632e0695b93e2a149a7fb60a77948162fce98334
        ports:
        - containerPort: 80
