apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:242a430ee2904ddc0302c57c8267da538f697f9c
        ports:
        - containerPort: 80
