apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:632e0695b93e2a149a7fb60a77948162fce98334
        ports:
        - containerPort: 80
