apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-phones:9a7a03948c7e71bf7a6faa370173b164a092546c
        ports:
        - containerPort: 80
